version: "2"

services:

  php:
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    image: skilldlabs/${PHP_IMAGE}
    links:
      - mysql:mysql
    depends_on:
      - mysql
    volumes:
      - ../../build:/var/www/html:z
      - ../modules:/var/www/html/modules/custom:z
      - ../themes:/var/www/html/themes/custom:z
      - ../../config:/var/www/html/config:z
    restart: always
    networks:
      - front

  nginx:
    image: skilldlabs/nginx:next
    container_name: "${COMPOSE_PROJECT_NAME}_web"
    links:
      - mysql:mysql
      - php:php
    depends_on:
      - php
    volumes_from:
      - php
    restart: always
    networks:
      - front

  mysql:
    image: percona:5.7
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    volumes:
      - /dev/shm/${COMPOSE_PROJECT_NAME}_mysql:/var/lib/mysql:Z
    environment:
      MYSQL_DATABASE: d8
      MYSQL_USER: d8
      MYSQL_PASSWORD: d8
      MYSQL_ROOT_PASSWORD: d8root
    restart: always
    networks:
      - front

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${IPRANGE}"
