version: "2"

services:

  php:
    image: skilldlabs/${PHP_IMAGE} # Allowed: 7.0, 5.6.
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    volumes:
      - ../../docroot:/var/www/html:z
    restart: always
    networks:
      - front

  nginx:
    image: skilldlabs/nginx:1.10.1
    container_name: "${COMPOSE_PROJECT_NAME}_web"
    links:
      - mysql:mysql
      - php:php
    depends_on:
      - php
    volumes_from:
      - php
    restart: always
    networks:
      - front

  mysql:
    image: percona:5.7
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    volumes:
      - ./docker-runtime/${COMPOSE_PROJECT_NAME}_mysql:/var/lib/mysql:Z
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - front

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${IPRANGE}"
